# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U8ROg7RimZvqpc9LkETmxy14ZKdFG9gp
"""

a="Akshay kumar"
a.find("k",2)

