# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U8ROg7RimZvqpc9LkETmxy14ZKdFG9gp
"""

a={"one":1,"two":2,"three":3}
print(a)
if "one" in a:
  del a["one"]
print(a)

